apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: zitadel
---
apiVersion: v1
kind: Namespace
metadata:
  name: hivebook
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
