services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      TRENCHES_DB_HOST: ${TRENCHES_DB_HOST}
      TRENCHES_DB_PORT: ${TRENCHES_DB_PORT}
      TRENCHES_DB_DATABASE: ${TRENCHES_DB_DATABASE}
      TRENCHES_DB_USERNAME: ${TRENCHES_DB_USERNAME}
      TRENCHES_DB_PASSWORD: ${TRENCHES_DB_PASSWORD}
      TRENCHES_DB_SCHEMA: ${TRENCHES_DB_SCHEMA}
    depends_on:
      psql:
        condition: service_healthy
    networks:
      - trenches
  psql:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TRENCHES_DB_DATABASE}
      POSTGRES_USER: ${TRENCHES_DB_USERNAME}
      POSTGRES_PASSWORD: ${TRENCHES_DB_PASSWORD}
    ports:
      - "${TRENCHES_DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${TRENCHES_DB_USERNAME} -d ${TRENCHES_DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - trenches

volumes:
  psql_volume:
networks:
  trenches:
